### ISSUE TITLE
libbacnet.a is missing functions

### ISSUE THREAD

**Issue by f0c300** [evensonbryan/meta-bacnet#1] opened 2016-10-17 14:42 UTC
Hello!
I was using this layer and recipe to cross compile the bacnet-stack and make the libbacnet.a available in my sdk.

It turned out running make clean before building the gateway demo cleans libbacnet.a and it is only "partially" rebuilt to match the gateway demo samples

I just changed the do_compile function to first build the gateway demo and then the "all" target and it seems fine for me now.

**Comment by evensonbryan** [comment] 2016-10-17 15:42
I can't reproduce the problem you're seeing.  Could you show the Bitbake build configuration for your setup?

I do remember having similar problems early on before I cleared PARALLEL_MAKE for the recipe.  Since the gateway demo defines BAC_ROUTING, the library needs to be rebuilt before the gateway binary.  With the standard PARALLEL_MAKE settings, "make lib" and "make gateway" would run in parallel and I'd get the missing functions error.  Could you run "bitbake -e bacnet-stack" to see what PARALLEL_MAKE is defined as when you build?

**Comment by evensonbryan** [comment] 2016-10-19 13:51
If you can provide more details on how this problem occurred and I am able to reproduce the problem, I will look into a fix.  However, I won't make a change without first being able to verify first.  Without additional information I'll assume that there was a separate tool setup issue that caused the problem and will close this issue stating that I can't reproduce the problem.

**Comment by f0c300** [comment] 2016-10-19 13:55
Hi,
Sorry for the delay I was not available yesterday.

The problem does not occur at build time but while linking libbacnet.a to my application later on, it complains that some functions are not found.

So apparently when building it with "make gateway" it does not include every bacnet function to the statically linked library.

**Comment by evensonbryan** [comment] 2016-10-19 14:09
You are correct, building the gateway demo enables different macros, which then produces a different libbacnet.a then when the rest of the demo applications are built.  The purpose of the base recipe is to build a working copy of all the demo applications, including the gateway demo.  If this in itself works, then we should close this issue.

If you do not need all (or any) of the demo applications for your purposes, then I would suggest using a .bbappend in your own layer to change what is built in the do_compile step.  You can also just build the library with "make lib" if that suits your purpose.

**Comment by f0c300** [comment] 2016-10-19 14:10
Oh ok then you can close the issue.

i used a bbappend with make al, was not aware of make lib, i might switch to that, thanks!

**Closed as completed** 2016-10-19 14:12 UTC
